service:
  name: serverless-mymemes

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  tracing:
    lambda: true
    apiGateway: true

  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}

  environment:
    MEMES_TABLE: Memes-${self:provider.stage}
    INDEX_NAME: MemesIndex-${self:provider.stage}
    IMAGES_S3_BUCKET: meme-images-asdf234-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

  iamRoleStatements:
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - "*"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  documentation:
    api:
      info:
        version: v1.0.0
        title: My Meme app
        description: Serverless application for uploading and categorizing memes

functions:

resources:
  Resources:
